AllCops:
  TargetRubyVersion: 2.7

Naming/FileName:
  Exclude:
    - Rakefile

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/ClassLength:
  Max: 256
  
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'